#! /usr/bin/env python

#This code will get the Oabcgatat Banes
import os
import csv
from bs4 import BeautifulSoup
import requests

import logging
import MySQLdb
import time
import re

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.common.by import By

#######################
# Global Declarations
#######################

delay = 2
timeout = 10
url="http://khadya.cg.nic.in/pdsonline/cgfsa/Report/FrmRation_Patra_Allot_VerificationDistWise_Aug14.aspx"
browser="Firefox"
logFile = __file__+'.log'
logLevel = logging.ERROR
logFormat = '%(asctime)s:[%(name)s|%(module)s|%(funcName)s|%(lineno)s|%(levelname)s]: %(message)s' #  %(asctime)s %(module)s:%(lineno)s %(funcName)s %(message)s"


#############
# Functions
#############

'''
def logInitialize():
  import logging
  logging.basicConfig(filename=logFile, level=logLevel, format=logFormat) # Mynk
'''

def loggerFetch(level=None):
  logger = logging.getLogger(__name__)

  if level:
    numeric_level = getattr(logging, level.upper(), None)
    if not isinstance(numeric_level, int):
      raise ValueError('Invalid log level: %s' % level)
    else:
      logger.setLevel(numeric_level)
  else:
    logger.setLevel(logLevel)

  # create console handler and set level to debug
  ch = logging.StreamHandler()
  ch.setLevel(logging.DEBUG)    # Mynk ???

  # create formatter e.g - FORMAT = '%(asctime)-15s %(clientip)s %(user)-8s %(message)s'
  formatter = logging.Formatter(logFormat)

  # add formatter to ch
  ch.setFormatter(formatter)

  # add ch to logger
  logger.addHandler(ch)

  return logger


def loggerTest(logger):
  logger.debug('debug message')
  logger.info('info message')
  logger.warn('warn message')
  logger.error('error message')
  logger.critical('critical message')
    

def argsFetch():
  '''
  Paser for the argument list that returns the args list
  '''
  import argparse

  parser = argparse.ArgumentParser(description='Jobcard script for crawling, downloading & parsing')
  parser.add_argument('-c', '--crawl', help='Crawl the pds reports', required=False, action='store_const', const=True)
  parser.add_argument('-p', '--prev', help='Parse the jobcards & musters downloaded', required=False, action='store_const', const=True)
  parser.add_argument('-v', '--visible', help='Make the browser visible', required=False, action='store_const', const=1)
  #parser.add_argument('-d', '--debug', help='Debug level (default=)', required=False)
  parser.add_argument('-l', '--log-level', help='Log level defining verbosity', required=False)
  parser.add_argument('-t', '--timeout', help='Time to wait before a page loads', required=False)
  parser.add_argument('-b', '--browser', help='Specify the browser to test with', required=False)
  parser.add_argument('-u', '--url', help='Specify the url to crawl', required=False)
  parser.add_argument('-d', '--directory', help='Specify directory to download html file to', required=False)

  args = vars(parser.parse_args())
  return args


def parserFinalize(parser):
  parser.close()


def dbInitialize():
  '''
  Connect to MySQL Database
  '''
  db = MySQLdb.connect(host="localhost", user="root", passwd="root123", db="surguja")
  db.autocommit(True)
  return db;

def dbFinalize(db):
  db.close()
  db.quit()

def displayInitialize(isVisible=0):
  from pyvirtualdisplay import Display
  
  display = Display(visible=isVisible, size=(600, 400))
  display.start()
  return display

def displayFinalize(display):
  display.stop()

def driverInitialize(browser="Firefox"):
  if browser == "Firefox":
    fp = webdriver.FirefoxProfile()
    fp.native_events_enabled = False
    fp.set_preference("browser.download.folderList",2)
    fp.set_preference("browser.download.manager.showWhenStarting",False)
    fp.set_preference("browser.download.dir", os.getcwd())
    fp.set_preference("browser.helperApps.neverAsk.saveToDisk", "application/vnd.ms-excel")

    driver = webdriver.Firefox(fp)
  elif browser == "PhantomJS":
    driver = webdriver.PhantomJS()
    driver.set_window_size(1120, 550)
  else:
    driver = webdriver.Chrome()

  driver.implicitly_wait(10)

  return driver

def driverFinalize(driver):
  driver.close()
  driver.quit()


def dbFetch(db, logger):
  # Query to get all the blocks
  query="select stateCode,districtCode,blockCode,name from blocks"
  logger.info('query: [%s]', query)
  cur=db.cursor()
  cur.execute(query)
  results = cur.fetchall()
  logger.info('results: [%s]', str(results))

  return results


def pdsFetch(driver, db, logger):
  '''
  Crawl the page for the khadya site and fecth the latest reports
  '''
  query="select b.pdsBlockCode,s.shopCode,b.name from pdsShops s,blocks b where b.blockCode=s.blockCode "
  logger.info('query: [%s]', query)
  cur=db.cursor()
  cur.execute(query)
  results = cur.fetchall()
  logger.info('results: [%s]', str(results))

  for row in results:
    pdsBlockCode=row[0]
    blockName=row[2]
    shopCode=row[1]
    filename = './html/'+shopCode+'.html'
    if os.path.isfile(filename):
      logger.info("Skipped [%s]" % filename)
      continue

    logger.info('Block Name:[%s] Shop Code:[%s]' % (blockName, shopCode))
    url="http://khadya.cg.nic.in/pdsonline/cgfsa/Report/FrmRation_Patra_Allot_VerificationDistWise_Aug14.aspx"
    logger.info('URL: [%s]', url)
    driver.get(url)
    time.sleep(2)
    driver.find_element_by_xpath("//select[@id='drpdist']/option[@value='39']").click()
    driver.find_element_by_xpath("//select[@id='ddlUrban_Rural']/option[@value='R']").click()
    time.sleep(2)
    driver.find_element_by_xpath("//select[@id='ddlNNN_Block']/option[@value='"+pdsBlockCode+"']").click()
    time.sleep(2)
    driver.find_element_by_xpath("//select[@id='ddlShopName']/option[@value='"+shopCode+"']").click()
    time.sleep(2)
    elem=driver.find_element_by_name("btnShowDetails")
    elem.send_keys(Keys.RETURN)
    time.sleep(2)
    html_source = driver.page_source
    raw_html=html_source.replace('<head>','<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>')
    with open(filename, "w") as html_file:
      html_file.write(raw_html.encode("UTF-8"))

def pdsFetchPrev(driver, db, logger, month="3"):
  '''
  Crawl the page for the khadya site and fecth the previous report given the month
  '''
  query="select b.pdsBlockCode,s.shopCode,b.name from pdsShops s,blocks b where b.blockCode=s.blockCode "
  logger.info('query: [%s]', query)
  cur=db.cursor()
  cur.execute(query)
  results = cur.fetchall()
  logger.info('results: [%s]', str(results))

  for row in results:
    pdsBlockCode=row[0]
    blockName=row[2]
    shopCode=row[1]

    if shopCode == "0":
      continue

    filename = './html/'+shopCode+'.html'
    if os.path.isfile(filename):
      logger.info("Skipped [%s]" % filename)
      continue

    logger.error('Block Name:[%s] Shop Code:[%s]' % (blockName, shopCode))
    url="http://khadya.cg.nic.in/rationcards/RationFC/RptShow_PreviousAllot_ShopWise.aspx"
    logger.info('URL: [%s]', url)

    driver.get(url)
    time.sleep(2)
    driver.find_element_by_xpath("//select[@id='DDdist']/option[@value='39']").click()
    driver.find_element_by_xpath("//select[@id='DDUR']/option[@value='R']").click()
    time.sleep(2)
    driver.find_element_by_xpath("//select[@id='DDBlock_NNN']/option[@value='"+pdsBlockCode+"']").click()
    time.sleep(2)
    print "Shopcode[", shopCode, "]"
    driver.find_element_by_xpath("//select[@id='DDShop']/option[@value='"+shopCode+"']").click()
    time.sleep(2)
    driver.find_element_by_xpath("//select[@id='DDYear']/option[@value='2015']").click()
    time.sleep(2)
    driver.find_element_by_xpath("//select[@id='DDMonth']/option[@value='" + month + "']").click()
    time.sleep(2)
    elem=driver.find_element_by_name("Button1")
    elem.send_keys(Keys.RETURN)
    time.sleep(2)
    html_source = driver.page_source
    raw_html=html_source.replace('<head>','<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>')
    with open(filename, "w") as html_file:
      html_file.write(raw_html.encode("UTF-8"))


def main():
  args = argsFetch()
  logger = loggerFetch(args.get('log_level'))
  logger.info('args: %s', str(args))

  db = dbInitialize()
  display = displayInitialize(args['visible'])
  driver = driverInitialize(browser)

  if args['prev']:
    pdsFetchPrev(driver, db, logger)
  else:
    pdsFetch(driver, db, logger)

  driverFinalize(driver)
  displayFinalize(display)
  dbFinalize(db)
  exit(0)

if __name__ == '__main__':
  main()

