CREATE TABLE `musters` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `finyear` varchar(2) DEFAULT NULL,
  `stateCode` varchar(2) DEFAULT NULL,
  `districtCode` varchar(2) DEFAULT NULL,
  `blockCode` varchar(3) DEFAULT NULL,
  `fullBlockCode` varchar(7) DEFAULT NULL,
  `musterNo` varchar(50) DEFAULT NULL,
  `panchayatCode` varchar(3) DEFAULT NULL,
  `musterType` varchar(5) DEFAULT '10',
  `workCode` varchar(40) DEFAULT NULL,
  `workName` varchar(1024) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `dateFrom` datetime DEFAULT NULL,
  `dateTo` datetime DEFAULT NULL,
  `isDownloaded` tinyint(1) DEFAULT '0',
  `isZeroAttendance` tinyint(1) DEFAULT '0',
  `crawlDate` datetime DEFAULT NULL,
  `downloadAttemptDate` datetime DEFAULT '2015-08-28 00:00:00',
  `downloadDate` datetime DEFAULT NULL,
  `wdProcessed` tinyint(1) DEFAULT '0',
  `wdError` tinyint(1) DEFAULT '0',
  `wdComplete` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `MUSTERKEY` (`finyear`,`fullBlockCode`,`musterNo`)
)
