CREATE TABLE `workDetails` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `finyear` varchar(2) DEFAULT NULL,
  `fullBlockCode` varchar(7) DEFAULT NULL,
  `musterNo` varchar(50) DEFAULT NULL,
  `musterIndex` tinyint(4) DEFAULT NULL,
  `isArchive` tinyint(1) DEFAULT '0',

  `stateCode` varchar(2) DEFAULT NULL,
  `districtCode` varchar(2) DEFAULT NULL,
  `blockCode` varchar(3) DEFAULT NULL,
  `panchayatCode` varchar(3) DEFAULT NULL,
  `stateName` varchar(40) DEFAULT NULL,
  `districtName` varchar(40) DEFAULT NULL,
  `blockName` varchar(40) DEFAULT NULL,
  `panchayatName` varchar(40) DEFAULT NULL,

  `workCode` varchar(40) DEFAULT NULL,
  `workName` varchar(1024) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,

  `name` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `aadharNo` varchar(30) DEFAULT NULL,
  `jobcard` varchar(30) DEFAULT NULL,
  `jcNumber` bigint(20) DEFAULT NULL,
  `daysWorked` tinyint(4) DEFAULT NULL,
  `dayWage` int(11) DEFAULT NULL,
  `totalWage` int(11) DEFAULT NULL,
  `accountNo` varchar(25) DEFAULT NULL,
  `wagelistNo` varchar(20) DEFAULT NULL,
  `bankNamePostOffice` varchar(256) DEFAULT NULL,
  `branchNamePostOfficeCode` varchar(256) DEFAULT NULL,
  `branchCodePostOfficeAddress` varchar(256) DEFAULT NULL,
  `musterStatus` varchar(20) DEFAULT NULL,

  `dateFrom` datetime DEFAULT NULL,
  `dateTo` datetime DEFAULT NULL,
  `firstSignatoryDate` datetime DEFAULT NULL,
  `secondSignatoryDate` datetime DEFAULT NULL,
  `transactionDate` datetime DEFAULT NULL,
  `bankProcessedDate` datetime DEFAULT NULL,
  `processedDate` datetime DEFAULT NULL,
  `paymentDate` datetime DEFAULT NULL,
  `creditedDate` datetime DEFAULT NULL,

  `ftoNo` varchar(50) DEFAULT NULL,
  `primaryAccountHolder` varchar(50) DEFAULT NULL,
  `rejectionReason` varchar(256) DEFAULT NULL,
  `ftoAccountNo` varchar(25) DEFAULT NULL,
  `ftoStatus` varchar(20) DEFAULT NULL,
  `ftoAmount` int(11) DEFAULT NULL,
  `referenceNo` varchar(40) DEFAULT NULL,
  `ftoName` varchar(256) DEFAULT NULL,
  `paymentMode` varchar(20) DEFAULT NULL,
  `wagelistCount` smallint(6) DEFAULT '0',

  `ftoMatchStatus` varchar(40) DEFAULT NULL,
  `matchComplete` tinyint(1) DEFAULT '0',
  `updateDate` datetime DEFAULT NULL,
  `needsAnalysis` tinyint(1) DEFAULT '0',
  `remarks` varchar(2048) DEFAULT NULL,
  INDEX `wdIndex` (`finyear`,`fullBlockCode`,`musterNo`,`musterIndex`,`isArchive`),

  PRIMARY KEY (`id`)
);
