nregaDB="nicnrega"
nregaRawDataDir="/home/libtech/nregaData/buckets/nrega-nic/stateName/districtName/"
nregaWebDir="/home/libtech/nregaData/nregaWeb/stateName/districtName/"
nregaWebDirRoot="/home/libtech/nregaData/nregaWeb/"
tempDir="/home/libtech/tempDir/"
