# Generated by Django 2.0.6 on 2018-08-12 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='downloadManager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nrega.DownloadManager'),
            preserve_default=False,
        ),
    ]
