# Generated by Django 2.0.6 on 2018-08-12 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0002_auto_20180812_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fto',
            name='downloadManager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nrega.DownloadManager'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='muster',
            name='downloadManager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nrega.DownloadManager'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wagelist',
            name='downloadManager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nrega.DownloadManager'),
            preserve_default=False,
        ),
    ]
