# Generated by Django 2.0.6 on 2018-08-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0003_auto_20180812_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlstate',
            name='iterateFinyear',
            field=models.BooleanField(default=True),
        ),
    ]
