# Generated by Django 2.0.6 on 2018-08-14 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0006_crawlstate_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finyear', models.CharField(max_length=2)),
                ('workDays', models.IntegerField(blank=True, null=True)),
                ('totalCredited', models.IntegerField(blank=True, null=True)),
                ('totalPending', models.IntegerField(blank=True, null=True)),
                ('totalRejected', models.IntegerField(blank=True, null=True)),
                ('totalWages', models.IntegerField(blank=True, null=True)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrega.Worker')),
            ],
            options={
                'db_table': 'workerStat',
            },
        ),
        migrations.AlterUniqueTogether(
            name='workerstat',
            unique_together={('worker', 'finyear')},
        ),
    ]
