# Generated by Django 2.0.6 on 2018-08-15 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0007_auto_20180814_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericreport',
            name='libtechTag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrega.LibtechTag'),
        ),
        migrations.AddField(
            model_name='genericreport',
            name='panchayat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrega.Panchayat'),
        ),
    ]
