# Generated by Django 2.0.6 on 2018-08-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0009_crawlstate_ispanchayatlevelprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlqueue',
            name='pending',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
