# Generated by Django 2.0.6 on 2018-08-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0010_crawlqueue_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlstate',
            name='threshold',
            field=models.IntegerField(blank=True, default=3600, null=True),
        ),
    ]
