# Generated by Django 2.0.6 on 2018-08-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0011_crawlstate_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlstate',
            name='objLimit',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
    ]
