# Generated by Django 2.0.6 on 2018-08-19 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0013_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='crawlState',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrega.CrawlState'),
        ),
    ]
