# Generated by Django 2.0.6 on 2018-08-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0014_task_crawlstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlqueue',
            name='isProcessDriven',
            field=models.BooleanField(default=False),
        ),
    ]
