# Generated by Django 2.0.6 on 2018-08-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0016_auto_20180820_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finyear',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
