# Generated by Django 2.0.6 on 2018-08-20 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0018_auto_20180821_0445'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='worker',
            unique_together={('jobcard', 'name', 'applicantNo')},
        ),
    ]
