# Generated by Django 2.0.6 on 2018-08-21 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0019_auto_20180821_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='apworkpayment',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrega.Worker'),
        ),
    ]
