# Generated by Django 2.0.6 on 2018-08-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0020_apworkpayment_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='apworkpayment',
            name='isDelayedPayment',
            field=models.BooleanField(default=False),
        ),
    ]
