# Generated by Django 2.0.6 on 2018-08-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0021_apworkpayment_isdelayedpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='libtechTag',
            field=models.ManyToManyField(blank=True, related_name='workerTag', to='nrega.LibtechTag'),
        ),
    ]
