# Generated by Django 2.0.6 on 2018-08-22 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0025_auto_20180822_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='crawlQueue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrega.CrawlQueue'),
        ),
    ]
