# Generated by Django 2.0.6 on 2018-08-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0026_auto_20180822_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='inProgress',
            field=models.BooleanField(default=False),
        ),
    ]
