broadcastsReportFile="/home/libtech/webroot/broadcasts/reports/broadcasts/index.html"
broadcastReportFilePath="/home/libtech/webroot/broadcasts/reports/broadcasts/"
includedir="/home/libtech/repo/includes/"
datadir="/home/libtech/gDrive/Chattisgarh/data/"
chaupalDataSummaryReportDir="/home/libtech/webroot/chaupalDataDashboard/reports/summary/"
chaupalDashboardLink='http://chaupal.libtech.info/' 
chaupalDataDashboardLink='http://chaupal.libtech.info/data/Summary/'
chaupalDataDashboardLimit=20 
dbBackupDir="/home/libtech/backup/data/db/"
dbNames="surguja,libtech,mahabubnagar"
maxExotelCallQueue=100 #This is the maximum number of calls that can be queued with exotel
maxTringoCallQueue=0 #This is the maximum number of calls that can be queued with exotel
