districtDBInitFile="/home/libtech/repo/nrega/init/district.sql"
nregaRawDataDir="/home/libtech/nregaData/buckets/districtName/raw/nrega/"
nregaWebDir="/home/libtech/nregaData/nregaWeb/stateName/districtName/"
nregaStaticWebDir="/home/libtech/nregaData/nregaWeb/stateName/districtName/"
tempDir="/home/libtech/webroot/nreganic.libtech.info/temp/"
searchIP="164.100.129.6"
