# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='stateShortCode',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
