# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0003_state_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
