# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0007_district_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('fullBlockCode', models.CharField(max_length=7, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.district')),
            ],
        ),
        migrations.CreateModel(
            name='panchayat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('fullPanchayatCode', models.CharField(max_length=10, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.block')),
            ],
        ),
    ]
