# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 04:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import nrega.models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0016_auto_20170414_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='panchayat',
            name='jobcardCrawlDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='panchayat',
            name='jobcardProcessDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='panchayat',
            name='jobcardRegisterFile',
            field=models.FileField(blank=True, null=True, upload_to=nrega.models.get_panchayat_upload_path),
        ),
        migrations.AlterField(
            model_name='block',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.District'),
        ),
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.State'),
        ),
        migrations.AlterField(
            model_name='panchayat',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.Block'),
        ),
    ]
