# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 06:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0020_auto_20170414_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musterNo', models.CharField(max_length=64)),
                ('finyear', models.CharField(max_length=2)),
                ('musterType', models.CharField(max_length=4)),
                ('workCode', models.CharField(max_length=128)),
                ('workName', models.CharField(max_length=2046)),
                ('dateFrom', models.DateField(default=datetime.date.today)),
                ('dateTo', models.DateField(default=datetime.date.today)),
                ('musterURL', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='block',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.District'),
        ),
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.State'),
        ),
        migrations.AlterField(
            model_name='panchayat',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.Block'),
        ),
        migrations.AddField(
            model_name='muster',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.Block'),
        ),
        migrations.AlterUniqueTogether(
            name='muster',
            unique_together=set([('musterNo', 'block', 'finyear')]),
        ),
    ]
