# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 08:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0024_auto_20170416_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='muster',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='muster',
            name='isDownloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='muster',
            name='isProcessed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='muster',
            name='musterDownloadAttemptDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='muster',
            name='musterDownloadDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.District'),
        ),
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.State'),
        ),
        migrations.AlterField(
            model_name='muster',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.Block'),
        ),
        migrations.AlterField(
            model_name='panchayat',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.Block'),
        ),
    ]
