# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0028_auto_20170417_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='accountFrozen',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='applicant',
            name='accountNo',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='applicant',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='bankBranchCode',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='applicant',
            name='bankBranchName',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='applicant',
            name='bankCode',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='applicant',
            name='bankName',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='applicant',
            name='caste',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='applicant',
            name='fatherHusbandName',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='applicant',
            name='gender',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='applicant',
            name='headOfHousehold',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='applicant',
            name='ifscCode',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='applicant',
            name='jcNo',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='micrCode',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='applicant',
            name='poAccountName',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='applicant',
            name='poAddress',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='applicant',
            name='poCode',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='applicant',
            name='poName',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='applicant',
            name='uid',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='applicant',
            name='village',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='jobcard',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='panchayat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.Panchayat'),
        ),
        migrations.AlterField(
            model_name='block',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.District'),
        ),
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.State'),
        ),
        migrations.AlterField(
            model_name='muster',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.Block'),
        ),
        migrations.AlterField(
            model_name='panchayat',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.Block'),
        ),
        migrations.AlterUniqueTogether(
            name='applicant',
            unique_together=set([('jobcard', 'applicantNo')]),
        ),
    ]
