# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import nrega.models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0037_auto_20170419_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='nicPanchayatReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportFile', models.FileField(blank=True, null=True, upload_to=nrega.models.get_panchayatreport_upload_path)),
                ('reportType', models.CharField(max_length=256)),
                ('finyear', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='applicant',
            name='panchayat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.Panchayat'),
        ),
        migrations.AlterField(
            model_name='block',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.District'),
        ),
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.State'),
        ),
        migrations.AlterField(
            model_name='muster',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.Block'),
        ),
        migrations.AlterField(
            model_name='muster',
            name='panchayat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrega.Panchayat'),
        ),
        migrations.AlterField(
            model_name='nicblockreport',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.Block'),
        ),
        migrations.AlterField(
            model_name='nicblockreport',
            name='reportType',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='panchayat',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.Block'),
        ),
        migrations.AddField(
            model_name='nicpanchayatreport',
            name='panchayat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.Panchayat'),
        ),
        migrations.AlterUniqueTogether(
            name='nicpanchayatreport',
            unique_together=set([('panchayat', 'reportType', 'finyear')]),
        ),
    ]
